- hosts: ae22:frieda23:hetzner
  roles:
    - basic-server
    - role: olsr
      tags: olsr
    - role: olsr2
      tags: olsr2
    - role: letsencrypt
      when: letsencrypt_certificates is defined
    - role: apache2-server
      when: apache2_sites is defined
    - role: mail-delivery
      when: mail_server is undefined

- hosts: gateway_server
  roles:
    - basic-server
    - role: olsr
      tags: olsr
    - role: olsr2
      tags: olsr2
    - python-module
    - gateway-server
    - nameserver-secondary
    - role: letsencrypt
      when: letsencrypt_certificates is defined
    - role: apache2-server
      when: apache2_sites is defined
    - role: mail-delivery

- hosts: ryoko.on:aqua.on:tamago.on:akito.on-i.de
  roles:
    - nameserver-resolver
    - virtualization-server

- hosts: jun.on
  roles:
    - domain-proxy
  tags: 
    - domain-proxy

- hosts: inez.on:maki.on
  roles:
    - backup-storage

- hosts: amano.on
  roles:
    - mitgliedsantrag
    - opennetca
    - git-server
  tags:
    - opennetca

- hosts: tenkawa.on
  roles:
    - media-mirror

- hosts: kinjo.on
  roles:
    - homematic

- hosts: goat.on
  roles:
    - buildbot-controller
  tags:
    - buildbot

- hosts: hoshino.on
  roles:
    - buildbot-worker
  tags:
    - buildbot

- hosts: ruri.on
  roles:
    - download-server

- hosts: kazama.on
  roles:
    - mailinglist-server

- hosts: gai.on-i.de
  roles:
    - wireguard-server
    # - gluon-l3-olsrv2-gateway  # Rolle beinhaltet derzeit nur Doku
  tags:
    - wireguard-server

# mediawiki in development
- hosts: hikaru.on
  roles:
    - mediawiki
    - www-server

- hosts: izumi.on
  roles:
    - service-discovery
    - nameserver-primary

# Gluon+Babel Tests
- hosts: itsuki.on-i.de
  roles:
    - basic-server
    # - gluon-l3  # Rolle beinhaltet derzeit nur Doku

# Mitgliederverwaltung Debian 10
- hosts: nagare.on
  roles:
    - mitgliederverwaltung

- hosts: howmei.on
  roles:
    - munin

- hosts: yurika.on
  roles:
    - ping-primary

- hosts: misumaru.on-i.de
  roles:
    - mail-server
