- name: restart networking
  service:
    name: networking
    state: restarted

- name: restart ferm
  service: name=ferm state=restarted

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted

- name: restart radvd
  service: name=radvd state=restarted
