- name: trac-config - Konfiguration anpassen
  ini_file:
    path: "{{ opennetdev_trac_path }}/conf/{{ opennetdev_trac_ini }}"
    section: "{{ item.sec }}"
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  with_items:
#    - { sec: "components", opt: "bitten.*", val: "enabled" }
    # TODO: reenable trac-announcer once available in Debian Buster
    #- { sec: "components", opt: "announcer.*", val: "enabled" }
#    - { sec: "", opt: "", val: "" }
    - { sec: "project", opt: "admin", val: "{{ opennetdev_trac_admin }}" }
    - { sec: "project", opt: "descr", val: "{{Â opennetdev_trac_desc }}" }
    - { sec: "project", opt: "footer", val: "{{ opennetdev_trac_footer }}" }
    - { sec: "project", opt: "icon", val: "site/{{ opennetdev_trac_icon }}" }
    - { sec: "project", opt: "url", val: "{{ opennetdev_trac_url }}" }
    - { sec: "header_logo", opt: "alt", val: "{{ opennetdev_trac_desc }}1" }
    - { sec: "header_logo", opt: "link", val: "/" }
    - { sec: "header_logo", opt: "src", val: "site/{{ opennetdev_trac_logo }}" }
    - { sec: "header_logo", opt: "height", val: "80" }
    - { sec: "notification", opt: "smtp_enabled", val: "enabled" }
    - { sec: "notification", opt: "email_sender", val: "SendmailEmailSender" }
    - { sec: "notification", opt: "smtp_from", val: "{{ opennetdev_trac_mailfrom }}" }
    - { sec: "notification", opt: "smtp_from_name", val: "{{ opennetdev_trac_desc }}" }
    - { sec: "ticket", opt: "default_component", val: "{{ opennetdev_trac_defaultcomponent }}" }
    - { sec: "ticket", opt: "default_type", val: "{{ opennetdev_trac_defaultticket }}" }
    - { sec: "timeline", opt: "ticket_show_component", val: "enabled" }
    - { sec: "timeline", opt: "ticket_show_details", val: "enabled" }
    - { sec: "trac", opt: "base_url", val: "{{ opennetdev_trac_url }}" }
    - { sec: "wiki", opt: "ignore_missing_pages", val: "enabled" }
  notify: reconfigure trac
